#!/bin/python3

import math
import os
import random
import re
import sys


def countingValleys(steps, path):
    # Write your code here
    val=0
    mt=0
    temp=0
    for i in path:
        if(i=="U"):
            mt=mt+1 
            if(val==mt):
                temp=temp+1 
        if(i=="D"):
            val=val+1
    return(temp)
    

steps = int(input().strip())

path = input()

result = countingValleys(steps, path)
